# Valores padrão para o Helm chart do Archivematica para OpenShift
# Este é um arquivo YAML formatado
# Declare variáveis a serem passadas para os templates

################################################################################
#                          Configurações Gerais                                #
################################################################################
general:
  # UID do usuário para execução dos contêineres
  # Escolha este valor com base no intervalo permitido do seu projeto OpenShift
  # (verifique a anotação openshift.io/sa.scc.uid-range)
  user_uid: "1001490000"

  # Namespace para instalação (será substituído pelo namespace de lançamento)
  namespace: npr-prodest-pds

################################################################################
#                   Configurações de segurança para OpenShift                  #
################################################################################
security:
  # ServiceAccount para os pods
  serviceAccount:
    # create: true
    name: "archivematica"
  serviceAccountAnyUID:
    # create: true
    name: "anyuid"
  # # SecurityContextConstraints para OpenShift
  # scc:
  #   # Usar SCC existente ou criar uma personalizada
  #   # Valores possíveis: "restricted", "nonroot", "anyuid", "custom"
  #   use: "anyuid"

  #   # Nome da SCC personalizada (se use: "custom")
  #   custom_name: "archivematica-scc"

################################################################################
#                   Configurações Dashboard                                    #
################################################################################
archivematica_dashboard:
  enabled: true
  image:
    repository: registry.prodest.es.gov.br/devops/archivematica-dashboard
    tag: "latest"
    pullPolicy: IfNotPresent
  env:
    - name: FORWARDED_ALLOW_IPS
      value: '*'
    - name: AM_GUNICORN_ACCESSLOG
      value: /dev/null
    - name: AM_GUNICORN_RELOAD
      value: "true"
    - name: AM_GUNICORN_RELOAD_ENGINE
      value: auto
    - name: ARCHIVEMATICA_DASHBOARD_EMAIL_PORT
      value: "587"
    - name: ARCHIVEMATICA_DASHBOARD_CLIENT_PORT
      value: "3306"
    - name: AM_GUNICORN_BIND
      value: "0.0.0.0:8001"
    - name: DJANGO_SETTINGS_MODULE
      value: "settings.local" # "settings.local"
    - name: AM_GUNICORN_LOGLEVEL
      value: "debug"
    - name: AM_GUNICORN_WORKERS
      value: "1"
    - name: AM_GUNICORN_PROC_NAME
      value: "archivematica-dashboard"
    - name: AM_GUNICORN_CHDIR
      value: "/src/src/archivematicaCommon/lib/"
    - name: ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE
      value: "MCP" # {{ .Values.mysql.db.name | quote }}
    - name: ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_SERVER
      value: "10.242.35.75:9200"
    - name: ARCHIVEMATICA_DASHBOARD_DASHBOARD_SEARCH_ENABLED
      value: "true"
################################################################################
#                  Configurações Storage Service                               #
################################################################################
archivematica_storage_service:
  enabled: true
  image:
    repository: registry.prodest.es.gov.br/devops/archivematica-storage-service
    tag: "latest"
    pullPolicy: IfNotPresent

  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  env:
    - name: DJANGO_SETTINGS_MODULE
      value: "storage_service.settings.local" #"storage_service.settings.local"
    - name: FORWARDED_ALLOW_IPS
      value: '*'
    - name: SS_GNUPG_HOME_PATH
      value: /var/archivematica/storage_service/.gnupg
    - name: SS_GUNICORN_ACCESSLOG
      value: /dev/null
    - name: SS_GUNICORN_RELOAD
      value: "true"
    - name: SS_GUNICORN_RELOAD_ENGINE
      value: auto
    - name: SS_GUNICORN_BIND
      value: "0.0.0.0:8002"
    # - name: SS_GUNICORN_LOGLEVEL
    #   value: "debug"
################################################################################
#                  Configurações ClamAV                                        #
################################################################################
clamav:
  enabled: true
  image:
    repository: clamav/clamav
    tag: "1.4_base"
  max_file_size: "2048"
  max_scan_size: "2048"
  max_stream_length: "2048"
  # Persistência para o ClamAV
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteOnce

################################################################################
#                  Configurações de rota para OpenShift                        #
################################################################################
route:
  enabled: true
  tls: true
  hostname: "archivematica.k8s-npr.es.gov.br"
  ss_hostname: "archivematica-ss.k8s-npr.es.gov.br"


################################################################################
#                    Configurações Elasticsearch                               #
################################################################################
elasticsearch:
  enabled: false
  image:
    repository: elasticsearch
    tag: "7.17.0"
    pullPolicy: IfNotPresent

  # Persistência para o Elasticsearch
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteOnce

################################################################################
#                     Configurações FITS                                       #
################################################################################
fits:
  enabled: true
  image:
    repository: artefactual/fits-ngserver
    tag: "0.8.4"
    pullPolicy: IfNotPresent

################################################################################
#                     Configurações Gearman                                    #
################################################################################
gearmand:
  enabled: true
  image:
    repository: artefactual/gearmand
    tag: "1.1.18-alpine"
    pullPolicy: IfNotPresent

  # Configurações do Gearman
  queue_type: "redis"
  redis_server: "redis"
  redis_port: 6379

################################################################################
#                     Configurações MCP Client                                 #
################################################################################
mcp_client:
  enabled: true
  image:
    repository: registry.prodest.es.gov.br/devops/archivematica-mcp-client
    tag: "latest"
    pullPolicy: IfNotPresent

  # Número de réplicas do MCP Client
  replicas: 1

  # Recursos para o MCP Client
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "1000m"
  env:
    - name: DJANGO_SETTINGS_MODULE
      value: "settings.common"
    - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_PORT
      value: "3306"
    - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_DATABASE
      value: MCP
    - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER
      value: "10.242.35.75:9200"
    - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_SEARCH_ENABLED
      value: "true"
    - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT
      value: "true"
    - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_PASS_BY_STREAM
      value: "false"
    - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_CLIENT_BACKEND
      value: clamdscanner
    - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_PROMETHEUS_BIND_PORT
      value: "7999"
    - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_PROMETHEUS_BIND_ADDRESS
      value: "0.0.0.0"
# - name: ARCHIVEMATICA_MCPCLIENT_EMAIL_BACKEND
#   value: "django.core.mail.backends.smtp.EmailBackend"
# - name: ARCHIVEMATICA_MCPCLIENT_EMAIL_HOST
#   value: "cernmx.cern.ch"
# - name: ARCHIVEMATICA_MCPCLIENT_EMAIL_PORT
#   value: "25"
# - name: ARCHIVEMATICA_MCPCLIENT_EMAIL_DEFAULT_FROM_EMAIL
#   value:
# - name: ARCHIVEMATICA_MCPCLIENT_EMAIL_SUBJECT_PREFIX
#   value: "DM AM Report"
# - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_METADATA_XML_VALIDATION_ENABLED
#   value: "true"
# - name: METADATA_XML_VALIDATION_SETTINGS_FILE
#   value: "/src/hack/submodules/archivematica-sampledata/xml-validation/xml_validation.py"
# - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_WATCHDIRECTORIES_CLIENTSCRIPTS
#   value: "analyze,characterize,clean_up_transfer_directory,compress_transfer,create_METS_manifest,create_SIP_from_transfer,create_transfer_backlog,extract_packages,normalize,remove_processed_transfer,scan_for_viruses,validate_transfer_compliance"
# - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_WATCHDIRECTORIES_PROCESSINGDIRECTORY
#   value: "/var/archivematica/sharedDirectory/watchedDirectories/activeProcessing"
# - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_WATCHDIRECTORIES_REJECTEDDIRECTORY
#   value: "/var/archivematica/sharedDirectory/watchedDirectories/rejected"
# - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_WATCHDIRECTORIES_TSUPLOADDIRECTORY
#   value: "/var/archivematica/sharedDirectory/watchedDirectories/upload"
# - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_WATCHDIRECTORIES_WAITINGFORUPLOADDIRECTORY
#   value: "/var/archivematica/sharedDirectory/watchedDirectories/waitingForUpload"
# - name: ARCHIVEMATICA_MCPCLIENT_CLIENTSCRIPTS_EXTRACTPACKAGES_EXTRACTCOMMAND
#   value: "7za x -y -o%d %f"
# - name: ARCHIVEMATICA_MCPCLIENT_CLIENTSCRIPTS_SCANFORVIRUSES_CLAMDHOST
#   value: "localhost" # Assumes ClamAV runs in the same pod or via localhost service
# - name: ARCHIVEMATICA_MCPCLIENT_CLIENTSCRIPTS_SCANFORVIRUSES_CLAMDPORT
#   value: "3310"
# - name: ARCHIVEMATICA_MCPCLIENT_CLIENTSCRIPTS_CHARACTERIZEANDEXTRACTMETADATA_FITSCOMMAND
#   value: "/usr/share/fits/fits.sh -i %file% -o %output%"
# - name: ARCHIVEMATICA_MCPCLIENT_CLIENTSCRIPTS_CHARACTERIZEANDEXTRACTMETADATA_FITSURL
#   value: "http://{{ include "archivematica.fullname" . }}-fits:2113/examine" # Assuming FITS runs as a separate service

################################################################################
#                     Configurações MCP Server                                 #
################################################################################
mcp_server:
  enabled: true
  image:
    repository: registry.prodest.es.gov.br/devops/archivematica-mcp-server
    tag: "latest"
    pullPolicy: IfNotPresent

  # Recursos para o MCP Server
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  # Environment variables para o MCP Server
  env:
    - name: ARCHIVEMATICA_MCPSERVER_SEARCH_ENABLED
      value: "true"
    - name: ARCHIVEMATICA_MCPSERVER_CLIENT_PORT
      value: "3306"
    - name: ARCHIVEMATICA_MCPSERVER_CLIENT_DATABASE
      value: "MCP"
    - name: ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_BIND_PORT
      value: "7999"
    - name: ARCHIVEMATICA_MCPSERVER_MCPSERVER_PROMETHEUS_BIND_ADDRESS
      value: "0.0.0.0"
    - name: DJANGO_SETTINGS_MODULE # Override DJANGO_SETTINGS_MODULE se necessário
      value: "settings.common"
################################################################################
#                     Configurações MySQL                                      #
################################################################################
mysql:
  enabled: true
  image:
    repository: percona #TODO: VERIFICAR PARA UTILIZAR O PERCONA:8.0
    tag: "8"
    pullPolicy: IfNotPresent

  # Configurações do banco de dados
  db:
    #name: "archivematica_db"
    user: "archivematica"
    password: "archivematica"
    rootPassword: "root_password"

  # URL de conexão para o Storage Service
  ss_db_url: "mysql://archivematica:archivematica@archivematica-mysql:3306/SS"

  # Persistência para o MySQL
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteOnce

################################################################################
#                     Configurações Redis                                      #
################################################################################
redis:
  enabled: true
  image:
    repository: redis
    tag: "6.0"
    pullPolicy: IfNotPresent

  # Persistência para o Redis
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteOnce


################################################################################
#                     Configurações volumes compartilhados                     #
################################################################################
shared_volumes:
  # Volume para dados do pipeline
  pipeline_data:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteMany

  # Volume para dados de staging
  staging_data:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteMany

  # Volume para dados de localização
  location_data:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteMany

  # Volume para compartilhamento de transferência
  transfer_share:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteMany

  # Volume para compartilhamento de armazenamento
  storage_share:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteMany

