apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archivematica.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.labels" . | nindent 4 }}
{{- if .Values.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.security.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.security.serviceAccountAnyUID.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anyuid-scc-binding
  labels:
    {{- include "archivematica.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.security.serviceAccountAnyUID.name }}
  namespace: {{ .Release.Namespace }}
